version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    restart: always
    networks:
      - node-nginx
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: 
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - "127.0.0.1:3305:3306"
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
     - node-nginx
  
  nginx: 
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks: 
      - node-nginx
    
networks:
  node-nginx:
    driver: bridge